### ISSUE TITLE
Restart timer

### ISSUE THREAD

**Issue by jmaricic** [talalmajali/react-native-countdown-component#12]
Is there a way to restart a timer once the countdown is finished or to manually start the countdown (on button press for example)?

**Comment by talalmajali** [comment]
@jmaricic You have to pass a new until value to the component, you can do this in onFinish callback, once the timer  finished you assign a new until value to the global state that until value came from.
Like if your until value came from the parent component state, in onFinish callback you reset that value, or if your until value came from redux reducer you need to dispatch an action to update that value.
I think this should do the trick for you.

**Comment by talalmajali** [comment]
@jmaricic I got your point
I have pushed a fix at bfcf2a6bc21cff4b55ecc9cfc353831a5ca7f7d8
and published as 1.7.3
Thanks

**Comment by aldocano29** [comment]
Hi, I tried to reset the timer, and yes... the timer gets a new until value when the countdown finishes, but it won't start counting down again.

**Comment by Tatandiaz13** [comment]
hi,

i have the same problem @aldocano29 , any solution ?

**Comment by Tatandiaz13** [comment]
if you still have the problem, this solution it work for me:

https://stackoverflow.com/questions/48674827/react-native-whats-the-best-way-to-remount-reset-reload-a-screen

it is a temporally solution.

**Comment by talalmajali** [comment]
@Tatandiaz13 @aldocano29 Will push fix soon

**Comment by talalmajali** [comment]
@Tatandiaz13 @aldocano29 this should be fixed with a4140c78f01ff55a0125238bab96e6e69442a76d
But if you pass a same last until value after the counter has finished it wont get restarted

**Comment by adybuciuman** [comment]
@talalmajali But if I need to pass the same value again? I'm doing a counter for a quiz and I need to reset the counter once the answer was saved.

**Comment by memanoj** [comment]
Try this https://github.com/talalmajali/react-native-countdown-component/issues/92#issuecomment-1467393540
