### ISSUE TITLE
Pause and Resume functionality

### ISSUE THREAD

**Issue by rahuldev761** [talalmajali/react-native-countdown-component#16]
Hi, it's a good countdown timer. But I want to know how I pause and resume this timer. Please tell me.

**Comment by talalmajali** [comment]
@rahuldev761 this functionality is not implemented in the component, you can fork it and add a prop called running and set the default to true, and you check this prop at componentWillReveiveProps, and  if this prop is false then you set the running interval otherwise you run it every second

**Comment by rahuldev761** [comment]
can you please add any snip of code. how I implement It. I am very new in react native and facing problem to implement. 
Thanx.
