### ISSUE TITLE
Padding, Margin

### ISSUE THREAD

**Issue by tigpalmas** [talalmajali/react-native-countdown-component#17]
is it possible to change padding and margin of the component ? i tried add style={{margin: 0, padding: 0}} unsuccessfully

**Comment by talalmajali** [comment]
@tigpalmas can you please show me an example for what you exactly you need to do, because margin and padding are working fine with me 
Thanks

**Comment by tigpalmas** [comment]
@talalmajali  im trying to achieve less space between the counter and my other components 
![countdownimage](https://user-images.githubusercontent.com/14172186/48944077-7b2d1c00-ef0c-11e8-9d23-5ef8bdfc1c80.png)

**Comment by talalmajali** [comment]
@tigpalmas with version 2.0.0+ you can override the digit style as well as digit text style

**Comment by lucasfalcaojump** [comment]
@talalmajali I'm trying to set digitStyle padding 0, but it doesn't work. What I'm trying to do is to end the space around the numbers, the red background on the attached file, please help me!
<img width="308" alt="captura de tela 2019-03-07 as 20 35 12" src="https://user-images.githubusercontent.com/23318402/53996799-9d902180-4118-11e9-901f-f2da12e49c3a.png">

**Comment by anniewey** [comment]
i managed to get rid of the padding by setting `height:'auto'` to the `digitStyle`. Setting 0 to margin and padding doesnt work.

```
digitStyle={{
                      borderWidth: 2,
                      borderColor: '#1CC625',
                      height:'auto'
                      //padding: 0,
                      //margin: 0,
}}
```
