### ISSUE TITLE
Font support

### ISSUE THREAD

**Issue by sweetcoco** [talalmajali/react-native-countdown-component#18]
Any plans?

**Comment by sweetcoco** [comment]
PR opened: 
https://github.com/talalmajali/react-native-countdown-component/pull/19

**Comment by talalmajali** [comment]
@sweetcoco Sorry for the late reply, will check the PR as soon as possible
Thanks :smile:

**Comment by Moji0098** [comment]
i cant change font 

```
                            <CountDown
                                    until={10000}
                                    onFinish={() => alert('finished')}
                                    onPress={() => alert('hello')}
                                    size={20}
                                    digitStyle={{
                                        backgroundColor:'#A52D53',
                                        borderRadius:50,
                                        fontFamily:'ISFBold'
                                    }}
                                    digitTxtStyle={{
                                        color:'#fff',
                                        fontFamily:'ISFBold'
                                    }}
                                    timeLabelStyle={{color: '#fff', fontWeight: 'bold' ,fontFamily:'ISFBold' }}
                                    timeToShow={['H', 'M ' , 'S']}
                                    timeLabels={{ h:'ساعت'  , m: 'دقیقه', s: 'ثانیه'}}
                                />
```

**Comment by hoangtrang1717** [comment]
> i cant change font
> 
> ```
> <CountDown
>     until={10000}
>     onFinish={() => alert('finished')}
>     onPress={() => alert('hello')}
>     size={20}
>     digitStyle={{
>     backgroundColor:'#A52D53',
>     borderRadius:50,
>     fontFamily:'ISFBold'
>    }}
>     digitTxtStyle={{
>              color:'#fff',
>              fontFamily:'ISFBold'
>     }}
>     timeLabelStyle={{color: '#fff', fontWeight: 'bold' ,fontFamily:'ISFBold' }}
>     timeToShow={['H', 'M ' , 'S']}
>     timeLabels={{ h:'ساعت'  , m: 'دقیقه', s: 'ثانیه'}}
>      >
> ```

In digitTxtStyle, change to digitTxtStyle={{
             color:'#fff',
             fontFamily:'ISFBold',
             fontWeight: 'normal'
    }},
as same as timeLableStyle.

**Comment by jamal-rahimzadegan** [comment]
for anyone who wants to change the font of digits, have to add this along the fontFamily:
fontWeight: 'normal'

**Comment by rayyanekaputra** [comment]
> for anyone who wants to change the font of digits, have to add this along the fontFamily: fontWeight: 'normal'

This works, thank you!! i thought i was too stupid 💀
