### ISSUE TITLE
Timer twice as fast. [ios]

### ISSUE THREAD

**Issue by vdongbin** [talalmajali/react-native-countdown-component#20]
It works properly in android.
But countdown timer goes twice as fast in ios.
-----------This is my code -------------

            <CountDown
              until={this.state.destroyTime}
              onFinish={() => this.timerAlert()}
              size={20}
              timeToShow={['M']}
              labelM={null}
              labelS={null}
              digitBgColor="transparent"
              digitTxtColor="#70a1ff"
            />

**Comment by Olcina** [comment]
Hi there, I don't experiment this issue. What testing device are you using? 

I'm testing on an Iphone6 through expo-client

**Comment by talalmajali** [comment]
@vdongbin what react-native version are you using?
is it happening in the ios simulator or real device?

**Comment by talalmajali** [comment]
@vdongbin please update to 2.1.1
