### ISSUE TITLE
timer waits 2 seconds until start counting down

### ISSUE THREAD

**Issue by dengue8830** [talalmajali/react-native-countdown-component#21]
React Native Environment Info:
    System:
      OS: Linux 4.4 Linux Mint 18 (Sarah)
      CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
      Memory: 1.49 GB / 15.65 GB
      Shell: Unknown - /usr/bin/fish
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 7, 8
        Build Tools: 19.0.0, 19.1.0, 20.0.0, 21.1.1, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-14 | ARM EABI v7a, android-16 | ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

**Comment by talalmajali** [comment]
@dengue8830 are you using the latest version of react-native-countdown-component ?

**Comment by dengue8830** [comment]
sorry for the delay

i was using 1.8.3 but now i can see a 3 days ago new version 2.0.0, i will try that

thanks!
