### ISSUE TITLE
anyway to show the standard : notation as a seperator? 

### ISSUE THREAD

**Issue by NanoMeko** [talalmajali/react-native-countdown-component#23]
Instead of the boxes , would it be possible to have a simple style mm:ss style? 
For example:      10:34
I set the background to white but it looks strange without the :

**Comment by Richi2293** [comment]
I think you would like something like that, it would also be useful to me.
You could put a Boolean variable to make this type of separator optional.

![image](https://user-images.githubusercontent.com/5848941/51382673-b0727680-1b17-11e9-88a6-d3d67e1fc9bf.png)

**Comment by azhararmar** [comment]
I have created pull request for this https://github.com/talalmajali/react-native-countdown-component/pull/24

Meanwhile my forked repo allows to set what you are seeking for, here is how I am doing it.

```
<CountDown
      until={3600}
      timeLabels={{m: '', h: '', s: ''}}
      digitStyle={{backgroundColor: 'transparent', width: 25, height: 25}}
      digitTxtStyle={{color: '#ffffff'}
      timeToShow={['H', 'M', 'S']}
      onFinish={() => alert('finished')}
      onPress={() => alert('hello')}
      separator={':'}
      size={20}
/>
```

**Comment by talalmajali** [comment]
@NanoMeko @Richi2293 it was added in this commit 6f1089090d7f4cac8beb7b2399988183f8f398b8
please update to 2.1.0
