### ISSUE TITLE
keep the CountDown running even if button pressed

### ISSUE THREAD

**Issue by h4m3d66** [talalmajali/react-native-countdown-component#27]
Hi,
is it possible to keep the CountDown running even if the back button pressed and component unmounted?

**Comment by talalmajali** [comment]
@h4m3d66 it's not the best practice to do this, if you keep the state of the component even when it's unmounted this will cause a memory leak in the app, also you will encounter performance issues with this, the best way to do it, you should render the component again and pass it the new until value
