### ISSUE TITLE
Bug with background

### ISSUE THREAD

**Issue by voroncv** [talalmajali/react-native-countdown-component#28]
If you exit the application, for example, open the notification center several times, the decrement of time will go faster exponentially
![ezgif-3-c05bca272aba](https://user-images.githubusercontent.com/20584352/52411979-84329000-2aee-11e9-97c4-0e520fefc01e.gif)

**Comment by talalmajali** [comment]
@voroncv  please update to version 2.1.1

**Comment by flogy** [comment]
Still having this issue with version `2.7.1`.
