### ISSUE TITLE
Digit styles inner content

### ISSUE THREAD

**Issue by lucasfalcaojump** [talalmajali/react-native-countdown-component#33]
Hey! I'm trying to reduce the space between the Separator and the Digit Style, but the space is measured by the font size as the following code:

renderDigit = (d) => {
    const {digitStyle, digitTxtStyle, size} = this.props;
    return (
      <View style={[
        styles.digitCont,
        digitStyle,
        **{width: size * 2.3, height: size * 2.6},**
      ]}>
        <Text style={[
          styles.digitTxt,
          {fontSize: size},
          digitTxtStyle,
        ]}>
          {d}
        </Text>
      </View>
    );
  };

Is there someway to change this to have more control over the component size by padding or something like this?

**Comment by Biplovkumar** [comment]
I think this is enough property {size={SCREEN_HEIGHT / 40}}
,If more than that,copy the library js file and edit it.

**Comment by talalmajali** [comment]
@lucasfalcaojump upgrade the component to the latest version, and you will be able to override the digit cont style

**Comment by shubhamk1997** [comment]
@talalmajali Not able to override the width and height for the spacing between separator and digits.
