### ISSUE TITLE
How to get the value that current looping ?

### ISSUE THREAD

**Issue by nolife08021** [talalmajali/react-native-countdown-component#38]
After the Timer start, how do i get the current value?
Like if i set until=10 , i want to set font color change to red when the time less than 5 ?

<CountDown
              digitStyle={{backgroundColor: '#FFF'}}
               until={10}
               timeToShow={['H','M','S']}
               onFinish={() => alert('Time's Up'}
               onPress={() => alert('hello')}
               size={20}
             />

**Comment by talalmajali** [comment]
@nolife08021 you can use onChange callback, `onChange={until => console.log(until)}`

**Comment by nolife08021** [comment]
i tried, but all i get was undefined. 

  <CountDown
              digitStyle={{backgroundColor: '#FFF'}}
               until={5}
               **onChange={until => console.log(until)}**
               timeToShow={['H','M','S']}
               onFinish={() => alert('Time's Up')}
               onPress={() => alert('hello')}
               size={20}
             />

**Comment by talalmajali** [comment]
@nolife08021 sorry i thought that i've merged a pull request for that, i'll push this feature today
thanks

**Comment by nolife08021** [comment]
@talalmajali  alright, i'll test tomorrow thanks

**Comment by mwojtow** [comment]
@talalmajali 
I remind, because I would like to use it too :)

**Comment by talalmajali** [comment]
@nolife08021 @mwojtow please upgrade to `2.3.0`, counter value will be passed to onChange

**Comment by nolife08021** [comment]
@talalmajali  Thanks
