### ISSUE TITLE
count down counts to negative values

### ISSUE THREAD

**Issue by mennaAppenza** [talalmajali/react-native-countdown-component#39]
timer count down to negative when the app is in the background and reopen it  3 seconds or less before the timer ends.

![56835532_2242148372511628_2806410933482553344_n](https://user-images.githubusercontent.com/47947587/56516002-a9ee0380-6539-11e9-9fe2-68d76c31fb3a.jpg)

**Comment by talalmajali** [comment]
@mennaAppenza please upgrade to `2.4.0`

**Comment by mennaAppenza** [comment]
@talalmajali thanks it's working fine now.
