### ISSUE TITLE
restart timer when countdown finishes?

### ISSUE THREAD

**Issue by panda0603** [talalmajali/react-native-countdown-component#41]
I wish to restart the timer automatically once the timer finishes.

I've looked at the closed issue #12 ,

but if you pass the same until value using onFinish prop, the countdown does not restart. 

However on many occasions the until value needs to be the same. 

How do we solve the issue?

**Comment by talalmajali** [comment]
@panda0603 please upgrade the component to `2.5.0` now you have `id` prop, if you send a different id to the component it will reset the timer, otherwise it will take all props and keeps the timer as it is.

**Comment by memanoj** [comment]
Try this https://github.com/talalmajali/react-native-countdown-component/issues/92#issuecomment-1467393540
