### ISSUE TITLE
onFinish() is not triggered when app is in background

### ISSUE THREAD

**Issue by Steve1820** [talalmajali/react-native-countdown-component#44]
Hey, great library!

The onFinish() prop is not triggered when the app is in the background.

Steve

**Comment by talalmajali** [comment]
@Steve1820 Hey, i think that we will have a different behavior between android and ios if i implement this, once the app went to the background you cannot execute any code for ios platform, on android you could do that for a few seconds after putting the app in the background, also on finish will be trigged when you come back again to the app
