### ISSUE TITLE
Could you please provide the starting interface

### ISSUE THREAD

**Issue by Marcello168** [talalmajali/react-native-countdown-component#45]

**Comment by talalmajali** [comment]
@Marcello168 Hello, What do you mean by starting interface?

**Comment by Marcello168** [comment]
> @Marcello168 Hello, What do you mean by starting interface?

Means The developer can control the start time instead of automatically starting

**Comment by talalmajali** [comment]
@Marcello168 you can pass false to `running` prop, so that the timer will not change unless you pass true to `running` prop again, does that makes sense?

**Comment by Marcello168** [comment]
OK，i see ，thans very much,

**Comment by Marcello168** [comment]
@talalmajali OK，i see ，thans very much,
