### ISSUE TITLE
react native countdown

### ISSUE THREAD

**Issue by mallik961** [talalmajali/react-native-countdown-component#46]
seconds min boxes show only single digit and not the second digit

**Comment by talalmajali** [comment]
@mallik961 what's the device name? and are you using custom styling for the component?

**Comment by talalmajali** [comment]
@mallik961  check this issue please, https://github.com/talalmajali/react-native-countdown-component/issues/49

**Comment by mallik961** [comment]
Hi Talalmajali/React-Native-Countdown-Component
I need to use countdown in my application i am using life cycles methods
and complex coding for simple use case i need a timer counter and i need to
change its speed and reset when i need but the component doesn't doing all
these things
