### ISSUE TITLE
Text cut off in oneplus mobile

### ISSUE THREAD

**Issue by 007vel** [talalmajali/react-native-countdown-component#49]
Countdown text not properly showing, text cut off in onpluse mobile,  view the screenshot, my timer countdown is 14 : 55 but it showing 1 : 5 

![Screenshot_20190630-130137](https://user-images.githubusercontent.com/39878179/60393757-d6289080-9b37-11e9-9f22-77d02761a82c.png)

**Comment by shahrajk** [comment]
share your code, please. @007vel

**Comment by chakkizza** [comment]
Hi, this is also happening for me .. and only for one plus mobile.
Here is the code: 

import CountDown from 'react-native-countdown-component';

<CountDown
                until={30}
                size={14}
                onFinish={null}
                digitTxtStyle={{color: '#000'}}
                timeToShow={['S']}
                timeLabels={{s: ''}}
              />

Also, I have added: 
declare module 'react-native-bottomsheet';
declare module 'react-native-countdown-component';

to the .d.ts file to get rid of the types error.

Please suggest.. This is a great library and works really well on other devices.

**Comment by chakkizza** [comment]
> Hi, this is also happening for me .. and only for one plus mobile.
> Here is the code:
> 
> import CountDown from 'react-native-countdown-component';
> 
> <CountDown
> until={30}
> size={14}
> onFinish={null}
> digitTxtStyle={{color: '#000'}}
> timeToShow={['S']}
> timeLabels={{s: ''}}
> />
> 
> Also, I have added:
> declare module 'react-native-bottomsheet';
> declare module 'react-native-countdown-component';
> 
> to the .d.ts file to get rid of the types error.
> 
> Please suggest.. This is a great library and works really well on other devices.

I could fix it by adding an extra space at the end of the digit in the library file.. However, this will get overridden in your next update. Please advise a better solution... this looks like one plus and oppo issue that gets fixed by using extra space at the end of the text

**Comment by chakkizza** [comment]
I have fixed this issue by explicitly passing the  fontfamily in the digitTxtStyle property.
This is probably because internally the library uses normal  Text component of React Native and renders default font.. Once we pass it the correct font that we are using across app, it works fine.
@007vel : Hope this helps.

**Comment by gogul-ct** [comment]
> I have fixed this issue by explicitly passing the fontfamily in the digitTxtStyle property.
> This is probably because internally the library uses normal Text component of React Native and renders default font.. Once we pass it the correct font that we are using across app, it works fine.
> @007vel : Hope this helps.

@chakkizza Is it 'fontfamily' or 'fontFamily' and is it a string? I passed the fontFamily used as a prop, but it is not reflected
