### ISSUE TITLE
I find that the component cannot reset the time if the time ends

### ISSUE THREAD

**Issue by FTD-ZF** [talalmajali/react-native-countdown-component#52]
At the end of the first time, go to the onFinish method, reset the time, and transfer different id and time. Debugging finds that the new data has been passed in, but there is no new time on the component for countdown, and the "00:00:00" is still displayed.    

 constructor(props) {
        super(props);
        this.timeid = '1',
        this.state = {
            endtime: 3,
        };
    }
onFinish() {
        this.timeid = '2'
        this.setState({
            endtime: 30,
        });

    }

 <CountDown
                    id={this.timeid}
                    size={12}
                    until={this.state.endtime}
                    onFinish={() => this.onFinish()}
                  
                    digitStyle={{ backgroundColor: 'black', borderWidth: 4, }}
                    digitTxtStyle={{ color: 'white', fontSize: 14 }}
                    timeLabelStyle={{ color: 'red', fontWeight: 'bold' }}
                    separatorStyle={{ color: 'black' }}
                    timeToShow={['H', 'M', 'S']}
                    timeLabels={{ m: null, s: null }}
                    showSeparator
                />

**Comment by saeedtkh** [comment]
I have the same problem, could you find any solution for it?

**Comment by talalmajali** [comment]
@FTD-ZF @saeedtkh you have to pass a new id for the component to start the timer again, make sure that you are using the latest version of the component

**Comment by talalmajali** [comment]
@saeedtkh @FTD-ZF please update the component to 2.5.1, it should be fixed now
