### ISSUE TITLE
Disable Console Log

### ISSUE THREAD

**Issue by Juliobobo** [talalmajali/react-native-countdown-component#53]
Hi, 

I use this countdown but when i see my console to analyse my logs, there are these lines "until = 2900".

How can i disable these logs ?

Thank you

**Comment by talalmajali** [comment]
@Juliobobo Hello, what's the version that you are using?

**Comment by Juliobobo** [comment]
@talalmajali  I'm using the version 2.5.1

**Comment by talalmajali** [comment]
@Juliobobo weird, there's no console log in the component

**Comment by keithmattix** [comment]
@talalmajali Did you push to npm before fixing things up in Github?

**Comment by talalmajali** [comment]
@keithmattix @Juliobobo there was a local change when i published the component, it should be fixed now on version `2.5.2`
Thank you for reporting :D
