### ISSUE TITLE
How to reset the timer on changing props?

### ISSUE THREAD

**Issue by Sandeep200995** [talalmajali/react-native-countdown-component#54]

**Comment by talalmajali** [comment]
@Sandeep200995 send a new `id` prop to the component

**Comment by kncarrier28** [comment]
I'm confused as to what you mean by 

> send a new id prop to the component

I've tried setting the id property to a state variable, but the countdown still does not reset when the state changes.

**Comment by memanoj** [comment]
Try this https://github.com/talalmajali/react-native-countdown-component/issues/92#issuecomment-1467393540
