### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by 15matias15** [talalmajali/react-native-countdown-component#56]
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: CountDown

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

**Comment by kristoff2016** [comment]
Hey, did you plan to update it? thanks

**Comment by lewatt23** [comment]
Hey please can you work on that ?

**Comment by dsernst** [comment]
See PR https://github.com/talalmajali/react-native-countdown-component/pull/48

**Comment by Ronaldofj** [comment]
The PR #48 continues opened? You has a prevision for the merge? Thanks

**Comment by khalidahmedshalabi** [comment]
Update it please

**Comment by fr3em1nd** [comment]
same issue here.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by fr3em1nd** [comment]
got this fixed based on this doc:

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html


![image](https://user-images.githubusercontent.com/2801155/73599701-27db4280-4581-11ea-997e-4dd74a970859.png)


it worked on my end. Here's my personal repo:

https://github.com/fr3em1nd/react-native-countdown-component/tree/componentWillReceiveProps-issue

**Comment by cnkyrpsgl** [comment]
Any news ?

**Comment by talalmajali** [comment]
@cnkyrpsgl @15matias15 @kristoff2016 @lewatt23 @dsernst please upgrade the component to `2.7.1`
