### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by JSchwerberg** [talalmajali/react-native-countdown-component#58]
Having no license on a repository means that you are disallowing the use of your component in any other projects, for any reason.  This is usually not what is intended. (https://choosealicense.com/no-permission/)

If this module is meant to be open source, I'd suggest a permissive license like [MIT](https://choosealicense.com/licenses/mit/).

Thanks!

**Comment by lmrarturo** [comment]
@JSchwerberg I created this pull request, adding MIT License. #59
