### ISSUE TITLE
How to get access to properties when using the onChange() function.

### ISSUE THREAD

**Issue by boep1963** [talalmajali/react-native-countdown-component#60]

**Comment by talalmajali** [comment]
@boep1963 what properties you want to access? you can only access `until` value using the onChange function

**Comment by boep1963** [comment]
HI,



Thanks for the reply. I want indeed access the until property (check the remaining time to send out a warning). This is how I implemented it



 <CountDown

              until={this.state.SB.Inspeeltijd}

              size={this.state.SB.InspeelCompBreedte || 48}

              onFinish={() => this.EindeInspeeltijd()}

              onChange={() => this.changeColor()}







changeColor() {

    ??? How to access the value until

  }







Regards,

met vriendelijke groet, 



Pierre




---- Op za, 05 okt 2019 14:04:57 +0200 Talal Majali <notifications@github.com> schreef ----


https://github.com/boep1963 what properties you want to access? you can only access until value using the onChange function

**Comment by talalmajali** [comment]
@boep1963 `onChange={until => this.changeColor(until)}`
