### ISSUE TITLE
Timer does't work properly when timeToShow is set

### ISSUE THREAD

**Issue by esdrasevt** [talalmajali/react-native-countdown-component#8]
When I set the timeToShow property, the timer show only the fields I included in the array, but the timer itself doesn't work. For instance, it set timeToShow to ['M', 'S'] and until to {600}, and the timer will countdown only 2 seconds instead. If I remove the timeToShow property and leave it as default, everything works fine.

**Comment by talalmajali** [comment]
@esdrasevt Fixed b363a47ed7990073dccc2d09345bd5af97f3eaa0
